// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cipherswarmagentsdkgo

// Generated from OpenAPI doc version 1.3 and generator version 2.796.4

import (
	"context"
	"fmt"
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/internal/config"
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/internal/hooks"
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/internal/utils"
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// The production server
	"https://{defaultHost}",
	// The insecure server
	"http://{hostAddress}:{hostPort}",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// CipherSwarmAgentSDK - CipherSwarm Agent API: The CipherSwarm Agent API is used to allow agents to connect to the CipherSwarm server.
type CipherSwarmAgentSDK struct {
	SDKVersion string
	// Agents API
	Agents *Agents
	// Attacks API
	Attacks *Attacks
	// Crackers API
	Crackers *Crackers
	// Tasks API
	Tasks *Tasks
	// Client API
	Client *Client

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*CipherSwarmAgentSDK)

// WithServerURL allows the overriding of the default server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *CipherSwarmAgentSDK) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *CipherSwarmAgentSDK) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *CipherSwarmAgentSDK) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithDefaultHost allows setting the defaultHost variable for url substitution
func WithDefaultHost(defaultHost string) SDKOption {
	return func(sdk *CipherSwarmAgentSDK) {
		for idx := range sdk.sdkConfiguration.ServerVariables {
			if _, ok := sdk.sdkConfiguration.ServerVariables[idx]["defaultHost"]; !ok {
				continue
			}

			sdk.sdkConfiguration.ServerVariables[idx]["defaultHost"] = fmt.Sprintf("%v", defaultHost)
		}
	}
}

// WithHostAddress allows setting the hostAddress variable for url substitution
func WithHostAddress(hostAddress string) SDKOption {
	return func(sdk *CipherSwarmAgentSDK) {
		for idx := range sdk.sdkConfiguration.ServerVariables {
			if _, ok := sdk.sdkConfiguration.ServerVariables[idx]["hostAddress"]; !ok {
				continue
			}

			sdk.sdkConfiguration.ServerVariables[idx]["hostAddress"] = fmt.Sprintf("%v", hostAddress)
		}
	}
}

// WithHostPort allows setting the hostPort variable for url substitution
func WithHostPort(hostPort string) SDKOption {
	return func(sdk *CipherSwarmAgentSDK) {
		for idx := range sdk.sdkConfiguration.ServerVariables {
			if _, ok := sdk.sdkConfiguration.ServerVariables[idx]["hostPort"]; !ok {
				continue
			}

			sdk.sdkConfiguration.ServerVariables[idx]["hostPort"] = fmt.Sprintf("%v", hostPort)
		}
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *CipherSwarmAgentSDK) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(bearerAuth string) SDKOption {
	return func(sdk *CipherSwarmAgentSDK) {
		security := components.Security{BearerAuth: bearerAuth}
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(&security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *CipherSwarmAgentSDK) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *CipherSwarmAgentSDK) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *CipherSwarmAgentSDK) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *CipherSwarmAgentSDK {
	sdk := &CipherSwarmAgentSDK{
		SDKVersion: "0.9.0",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 0.9.0 2.796.4 1.3 github.com/unclesp1d3r/cipherswarm-agent-sdk-go",
			ServerList: ServerList,
			ServerVariables: []map[string]string{
				{
					"defaultHost": "cipherswarm.com",
				},
				{
					"hostAddress": "localhost",
					"hostPort":    "8080",
				},
			},
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	currentServerURL, _ := sdk.sdkConfiguration.GetServerDetails()
	serverURL := currentServerURL
	serverURL, sdk.sdkConfiguration.Client = sdk.hooks.SDKInit(currentServerURL, sdk.sdkConfiguration.Client)
	if currentServerURL != serverURL {
		sdk.sdkConfiguration.ServerURL = serverURL
	}

	sdk.Agents = newAgents(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Attacks = newAttacks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Crackers = newCrackers(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Tasks = newTasks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Client = newClient(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
