// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

// AuthenticateResponseBody - successful
type AuthenticateResponseBody struct {
	Authenticated bool  `json:"authenticated"`
	AgentID       int64 `json:"agent_id"`
}

func (a *AuthenticateResponseBody) GetAuthenticated() bool {
	if a == nil {
		return false
	}
	return a.Authenticated
}

func (a *AuthenticateResponseBody) GetAgentID() int64 {
	if a == nil {
		return 0
	}
	return a.AgentID
}

type AuthenticateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful
	Object *AuthenticateResponseBody
}

func (a *AuthenticateResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AuthenticateResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AuthenticateResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AuthenticateResponse) GetObject() *AuthenticateResponseBody {
	if a == nil {
		return nil
	}
	return a.Object
}
