// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type CheckForCrackerUpdateRequest struct {
	// operating_system
	OperatingSystem *string `queryParam:"style=form,explode=true,name=operating_system"`
	// version
	Version *string `queryParam:"style=form,explode=true,name=version"`
}

func (c *CheckForCrackerUpdateRequest) GetOperatingSystem() *string {
	if c == nil {
		return nil
	}
	return c.OperatingSystem
}

func (c *CheckForCrackerUpdateRequest) GetVersion() *string {
	if c == nil {
		return nil
	}
	return c.Version
}

type CheckForCrackerUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// operating system not found
	CrackerUpdate *components.CrackerUpdate
}

func (c *CheckForCrackerUpdateResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CheckForCrackerUpdateResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CheckForCrackerUpdateResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CheckForCrackerUpdateResponse) GetCrackerUpdate() *components.CrackerUpdate {
	if c == nil {
		return nil
	}
	return c.CrackerUpdate
}
