// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type GetAgentRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetAgentRequest) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}

type GetAgentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful
	Agent *components.Agent
}

func (g *GetAgentResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAgentResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAgentResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAgentResponse) GetAgent() *components.Agent {
	if g == nil {
		return nil
	}
	return g.Agent
}
