// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

// GetConfigurationResponseBody - successful
type GetConfigurationResponseBody struct {
	Config components.AdvancedAgentConfiguration `json:"config"`
	// The minimum accepted version of the API
	APIVersion int64 `json:"api_version"`
}

func (g *GetConfigurationResponseBody) GetConfig() components.AdvancedAgentConfiguration {
	if g == nil {
		return components.AdvancedAgentConfiguration{}
	}
	return g.Config
}

func (g *GetConfigurationResponseBody) GetAPIVersion() int64 {
	if g == nil {
		return 0
	}
	return g.APIVersion
}

type GetConfigurationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful
	Object *GetConfigurationResponseBody
}

func (g *GetConfigurationResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetConfigurationResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetConfigurationResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetConfigurationResponse) GetObject() *GetConfigurationResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
