// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/internal/utils"
	"net/http"
	"time"
)

// GetHealthResponseBody - healthy
type GetHealthResponseBody struct {
	// Overall health status (ok or degraded)
	Status string `json:"status"`
	// API version
	APIVersion int64 `json:"api_version"`
	// Server timestamp
	Timestamp time.Time `json:"timestamp"`
	// Database health (healthy or unhealthy)
	Database string `json:"database"`
}

func (g GetHealthResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetHealthResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetHealthResponseBody) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetHealthResponseBody) GetAPIVersion() int64 {
	if g == nil {
		return 0
	}
	return g.APIVersion
}

func (g *GetHealthResponseBody) GetTimestamp() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.Timestamp
}

func (g *GetHealthResponseBody) GetDatabase() string {
	if g == nil {
		return ""
	}
	return g.Database
}

type GetHealthResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// healthy
	Object *GetHealthResponseBody
}

func (g *GetHealthResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetHealthResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetHealthResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetHealthResponse) GetObject() *GetHealthResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
