// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type GetTaskRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetTaskRequest) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}

type GetTaskResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful
	Task *components.Task
}

func (g *GetTaskResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetTaskResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetTaskResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetTaskResponse) GetTask() *components.Task {
	if g == nil {
		return nil
	}
	return g.Task
}
