// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type SendCrackRequest struct {
	// id
	ID            int64                    `pathParam:"style=simple,explode=false,name=id"`
	HashcatResult components.HashcatResult `request:"mediaType=application/json"`
}

func (s *SendCrackRequest) GetID() int64 {
	if s == nil {
		return 0
	}
	return s.ID
}

func (s *SendCrackRequest) GetHashcatResult() components.HashcatResult {
	if s == nil {
		return components.HashcatResult{}
	}
	return s.HashcatResult
}

type SendCrackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (s *SendCrackResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SendCrackResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SendCrackResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}
