// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type SendHeartbeatRequest struct {
	// id
	ID                    int64                             `pathParam:"style=simple,explode=false,name=id"`
	AgentHeartbeatRequest *components.AgentHeartbeatRequest `request:"mediaType=application/json"`
}

func (s *SendHeartbeatRequest) GetID() int64 {
	if s == nil {
		return 0
	}
	return s.ID
}

func (s *SendHeartbeatRequest) GetAgentHeartbeatRequest() *components.AgentHeartbeatRequest {
	if s == nil {
		return nil
	}
	return s.AgentHeartbeatRequest
}

type SendHeartbeatResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful, but with server feedback
	HeartbeatResponse *components.HeartbeatResponse
}

func (s *SendHeartbeatResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SendHeartbeatResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SendHeartbeatResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SendHeartbeatResponse) GetHeartbeatResponse() *components.HeartbeatResponse {
	if s == nil {
		return nil
	}
	return s.HeartbeatResponse
}
