// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type SendStatusRequest struct {
	// id
	ID         int64                 `pathParam:"style=simple,explode=false,name=id"`
	TaskStatus components.TaskStatus `request:"mediaType=application/json"`
}

func (s *SendStatusRequest) GetID() int64 {
	if s == nil {
		return 0
	}
	return s.ID
}

func (s *SendStatusRequest) GetTaskStatus() components.TaskStatus {
	if s == nil {
		return components.TaskStatus{}
	}
	return s.TaskStatus
}

type SendStatusResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (s *SendStatusResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SendStatusResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SendStatusResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}
