// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type SetAgentShutdownRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (s *SetAgentShutdownRequest) GetID() int64 {
	if s == nil {
		return 0
	}
	return s.ID
}

type SetAgentShutdownResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (s *SetAgentShutdownResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SetAgentShutdownResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SetAgentShutdownResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}
