// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type SetTaskAbandonedRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (s *SetTaskAbandonedRequest) GetID() int64 {
	if s == nil {
		return 0
	}
	return s.ID
}

// SetTaskAbandonedResponseBody - successful
type SetTaskAbandonedResponseBody struct {
	Success *bool   `json:"success,omitempty"`
	State   *string `json:"state,omitempty"`
}

func (s *SetTaskAbandonedResponseBody) GetSuccess() *bool {
	if s == nil {
		return nil
	}
	return s.Success
}

func (s *SetTaskAbandonedResponseBody) GetState() *string {
	if s == nil {
		return nil
	}
	return s.State
}

type SetTaskAbandonedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful
	Object *SetTaskAbandonedResponseBody
}

func (s *SetTaskAbandonedResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SetTaskAbandonedResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SetTaskAbandonedResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SetTaskAbandonedResponse) GetObject() *SetTaskAbandonedResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
