// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type SetTaskAbandonedRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (s *SetTaskAbandonedRequest) GetID() int64 {
	if s == nil {
		return 0
	}
	return s.ID
}

type SetTaskAbandonedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful
	TaskAbandonResponse *components.TaskAbandonResponse
}

func (s *SetTaskAbandonedResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SetTaskAbandonedResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SetTaskAbandonedResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SetTaskAbandonedResponse) GetTaskAbandonResponse() *components.TaskAbandonResponse {
	if s == nil {
		return nil
	}
	return s.TaskAbandonResponse
}
