// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type SubmitErrorAgentRequest struct {
	// id
	ID                 int64                         `pathParam:"style=simple,explode=false,name=id"`
	SubmitErrorRequest components.SubmitErrorRequest `request:"mediaType=application/json"`
}

func (s *SubmitErrorAgentRequest) GetID() int64 {
	if s == nil {
		return 0
	}
	return s.ID
}

func (s *SubmitErrorAgentRequest) GetSubmitErrorRequest() components.SubmitErrorRequest {
	if s == nil {
		return components.SubmitErrorRequest{}
	}
	return s.SubmitErrorRequest
}

type SubmitErrorAgentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (s *SubmitErrorAgentResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SubmitErrorAgentResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SubmitErrorAgentResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}
