// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type UpdateAgentRequest struct {
	// id
	ID                 int64                         `pathParam:"style=simple,explode=false,name=id"`
	UpdateAgentRequest components.UpdateAgentRequest `request:"mediaType=application/json"`
}

func (u *UpdateAgentRequest) GetID() int64 {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdateAgentRequest) GetUpdateAgentRequest() components.UpdateAgentRequest {
	if u == nil {
		return components.UpdateAgentRequest{}
	}
	return u.UpdateAgentRequest
}

type UpdateAgentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful
	Agent *components.Agent
}

func (u *UpdateAgentResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateAgentResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateAgentResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateAgentResponse) GetAgent() *components.Agent {
	if u == nil {
		return nil
	}
	return u.Agent
}
