// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

// UpdateAgentRequestBody - Agent system information
type UpdateAgentRequestBody struct {
	// The id of the agent
	ID int64 `json:"id"`
	// The hostname of the agent
	HostName string `json:"host_name"`
	// The signature of the client
	ClientSignature string `json:"client_signature"`
	// The operating system of the agent
	OperatingSystem string   `json:"operating_system"`
	Devices         []string `json:"devices"`
}

func (u *UpdateAgentRequestBody) GetID() int64 {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdateAgentRequestBody) GetHostName() string {
	if u == nil {
		return ""
	}
	return u.HostName
}

func (u *UpdateAgentRequestBody) GetClientSignature() string {
	if u == nil {
		return ""
	}
	return u.ClientSignature
}

func (u *UpdateAgentRequestBody) GetOperatingSystem() string {
	if u == nil {
		return ""
	}
	return u.OperatingSystem
}

func (u *UpdateAgentRequestBody) GetDevices() []string {
	if u == nil {
		return []string{}
	}
	return u.Devices
}

type UpdateAgentRequest struct {
	// id
	ID          int64                  `pathParam:"style=simple,explode=false,name=id"`
	RequestBody UpdateAgentRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateAgentRequest) GetID() int64 {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdateAgentRequest) GetRequestBody() UpdateAgentRequestBody {
	if u == nil {
		return UpdateAgentRequestBody{}
	}
	return u.RequestBody
}

type UpdateAgentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful
	Agent *components.Agent
}

func (u *UpdateAgentResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateAgentResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateAgentResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateAgentResponse) GetAgent() *components.Agent {
	if u == nil {
		return nil
	}
	return u.Agent
}
