// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type ErrorObject struct {
	Error_               string         `json:"error"`
	AdditionalProperties map[string]any `additionalProperties:"true" json:"-"`
}

var _ error = &ErrorObject{}

func (e *ErrorObject) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
