// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
	"time"
)

// GetHealthResponseBody - degraded
type GetHealthResponseBody struct {
	// Overall health status (ok or degraded)
	Status string `json:"status"`
	// API version
	APIVersion int64 `json:"api_version"`
	// Server timestamp
	Timestamp time.Time `json:"timestamp"`
	// Database health (healthy or unhealthy)
	Database string `json:"database"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetHealthResponseBody{}

func (e *GetHealthResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
