// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// SetTaskAbandonedResponseBody - already completed
type SetTaskAbandonedResponseBody struct {
	Error_  *string  `json:"error,omitempty"`
	Details []string `json:"details,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &SetTaskAbandonedResponseBody{}

func (e *SetTaskAbandonedResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
