// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// TaskAbandonError - Error response when a task cannot be abandoned
type TaskAbandonError struct {
	Error_  *string  `json:"error,omitempty"`
	Details []string `json:"details,omitempty"`
}

var _ error = &TaskAbandonError{}

func (e *TaskAbandonError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
