// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// State - The state of the agent
type State string

const (
	StatePending State = "pending"
	StateActive  State = "active"
	StateStopped State = "stopped"
	StateError   State = "error"
)

func (e State) ToPointer() *State {
	return &e
}
func (e *State) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "active":
		fallthrough
	case "stopped":
		fallthrough
	case "error":
		*e = State(v)
		return nil
	default:
		return fmt.Errorf("invalid value for State: %v", v)
	}
}

type Agent struct {
	// The id of the agent
	ID int64 `json:"id"`
	// The hostname of the agent
	HostName string `json:"host_name"`
	// The signature of the client
	ClientSignature string `json:"client_signature"`
	// The state of the agent
	State State `json:"state"`
	// The operating system of the agent
	OperatingSystem       string                     `json:"operating_system"`
	Devices               []string                   `json:"devices"`
	AdvancedConfiguration AdvancedAgentConfiguration `json:"advanced_configuration"`
}

func (a *Agent) GetID() int64 {
	if a == nil {
		return 0
	}
	return a.ID
}

func (a *Agent) GetHostName() string {
	if a == nil {
		return ""
	}
	return a.HostName
}

func (a *Agent) GetClientSignature() string {
	if a == nil {
		return ""
	}
	return a.ClientSignature
}

func (a *Agent) GetState() State {
	if a == nil {
		return State("")
	}
	return a.State
}

func (a *Agent) GetOperatingSystem() string {
	if a == nil {
		return ""
	}
	return a.OperatingSystem
}

func (a *Agent) GetDevices() []string {
	if a == nil {
		return []string{}
	}
	return a.Devices
}

func (a *Agent) GetAdvancedConfiguration() AdvancedAgentConfiguration {
	if a == nil {
		return AdvancedAgentConfiguration{}
	}
	return a.AdvancedConfiguration
}
