// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentHeartbeatRequest - Optional activity state update sent with an agent heartbeat
type AgentHeartbeatRequest struct {
	// Current agent activity state. Known values: starting, benchmarking, updating, downloading, waiting, cracking, stopping. Future versions may support additional values.
	Activity *string `json:"activity,omitempty"`
}

func (a *AgentHeartbeatRequest) GetActivity() *string {
	if a == nil {
		return nil
	}
	return a.Activity
}
