// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/internal/utils"
)

// AttackMode - Attack mode name
type AttackMode string

const (
	AttackModeDictionary       AttackMode = "dictionary"
	AttackModeMask             AttackMode = "mask"
	AttackModeHybridDictionary AttackMode = "hybrid_dictionary"
	AttackModeHybridMask       AttackMode = "hybrid_mask"
)

func (e AttackMode) ToPointer() *AttackMode {
	return &e
}
func (e *AttackMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "dictionary":
		fallthrough
	case "mask":
		fallthrough
	case "hybrid_dictionary":
		fallthrough
	case "hybrid_mask":
		*e = AttackMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AttackMode: %v", v)
	}
}

type Attack struct {
	// The id of the attack
	ID int64 `json:"id"`
	// Attack mode name
	AttackMode *AttackMode `default:"dictionary" json:"attack_mode"`
	// hashcat attack mode
	AttackModeHashcat *int64 `default:"0" json:"attack_mode_hashcat"`
	// A hashcat mask string
	Mask *string `default:"" json:"mask"`
	// Enable hashcat increment mode
	IncrementMode *bool `default:"false" json:"increment_mode"`
	// The start of the increment range
	IncrementMinimum int64 `json:"increment_minimum"`
	// The end of the increment range
	IncrementMaximum int64 `json:"increment_maximum"`
	// Enable hashcat optimized mode
	Optimized *bool `default:"false" json:"optimized"`
	// Enable hashcat slow candidate generators
	SlowCandidateGenerators *bool `default:"false" json:"slow_candidate_generators"`
	// The hashcat workload profile
	WorkloadProfile *int64 `default:"3" json:"workload_profile"`
	// Disable hashcat markov mode
	DisableMarkov *bool `default:"false" json:"disable_markov"`
	// Enable hashcat classic markov mode
	ClassicMarkov *bool `default:"false" json:"classic_markov"`
	// The hashcat markov threshold
	MarkovThreshold *int64 `default:"0" json:"markov_threshold"`
	// The left-hand rule for combinator attacks
	LeftRule *string `default:"" json:"left_rule"`
	// The right-hand rule for combinator attacks
	RightRule *string `default:"" json:"right_rule"`
	// Custom charset 1 for hashcat mask attacks
	CustomCharset1 *string `default:"" json:"custom_charset_1"`
	// Custom charset 2 for hashcat mask attacks
	CustomCharset2 *string `default:"" json:"custom_charset_2"`
	// Custom charset 3 for hashcat mask attacks
	CustomCharset3 *string `default:"" json:"custom_charset_3"`
	// Custom charset 4 for hashcat mask attacks
	CustomCharset4 *string `default:"" json:"custom_charset_4"`
	// The id of the hash list
	HashListID int64               `json:"hash_list_id"`
	WordList   *AttackResourceFile `json:"word_list,omitempty"`
	RuleList   *AttackResourceFile `json:"rule_list,omitempty"`
	MaskList   *AttackResourceFile `json:"mask_list,omitempty"`
	// The hashcat hash mode
	HashMode *int64 `default:"0" json:"hash_mode"`
	// The download URL for the hash list
	HashListURL *string `json:"hash_list_url"`
	// The MD5 checksum of the hash list
	HashListChecksum *string `json:"hash_list_checksum"`
	// The URL to the attack
	URL *string `json:"url"`
}

func (a Attack) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Attack) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Attack) GetID() int64 {
	if a == nil {
		return 0
	}
	return a.ID
}

func (a *Attack) GetAttackMode() *AttackMode {
	if a == nil {
		return nil
	}
	return a.AttackMode
}

func (a *Attack) GetAttackModeHashcat() *int64 {
	if a == nil {
		return nil
	}
	return a.AttackModeHashcat
}

func (a *Attack) GetMask() *string {
	if a == nil {
		return nil
	}
	return a.Mask
}

func (a *Attack) GetIncrementMode() *bool {
	if a == nil {
		return nil
	}
	return a.IncrementMode
}

func (a *Attack) GetIncrementMinimum() int64 {
	if a == nil {
		return 0
	}
	return a.IncrementMinimum
}

func (a *Attack) GetIncrementMaximum() int64 {
	if a == nil {
		return 0
	}
	return a.IncrementMaximum
}

func (a *Attack) GetOptimized() *bool {
	if a == nil {
		return nil
	}
	return a.Optimized
}

func (a *Attack) GetSlowCandidateGenerators() *bool {
	if a == nil {
		return nil
	}
	return a.SlowCandidateGenerators
}

func (a *Attack) GetWorkloadProfile() *int64 {
	if a == nil {
		return nil
	}
	return a.WorkloadProfile
}

func (a *Attack) GetDisableMarkov() *bool {
	if a == nil {
		return nil
	}
	return a.DisableMarkov
}

func (a *Attack) GetClassicMarkov() *bool {
	if a == nil {
		return nil
	}
	return a.ClassicMarkov
}

func (a *Attack) GetMarkovThreshold() *int64 {
	if a == nil {
		return nil
	}
	return a.MarkovThreshold
}

func (a *Attack) GetLeftRule() *string {
	if a == nil {
		return nil
	}
	return a.LeftRule
}

func (a *Attack) GetRightRule() *string {
	if a == nil {
		return nil
	}
	return a.RightRule
}

func (a *Attack) GetCustomCharset1() *string {
	if a == nil {
		return nil
	}
	return a.CustomCharset1
}

func (a *Attack) GetCustomCharset2() *string {
	if a == nil {
		return nil
	}
	return a.CustomCharset2
}

func (a *Attack) GetCustomCharset3() *string {
	if a == nil {
		return nil
	}
	return a.CustomCharset3
}

func (a *Attack) GetCustomCharset4() *string {
	if a == nil {
		return nil
	}
	return a.CustomCharset4
}

func (a *Attack) GetHashListID() int64 {
	if a == nil {
		return 0
	}
	return a.HashListID
}

func (a *Attack) GetWordList() *AttackResourceFile {
	if a == nil {
		return nil
	}
	return a.WordList
}

func (a *Attack) GetRuleList() *AttackResourceFile {
	if a == nil {
		return nil
	}
	return a.RuleList
}

func (a *Attack) GetMaskList() *AttackResourceFile {
	if a == nil {
		return nil
	}
	return a.MaskList
}

func (a *Attack) GetHashMode() *int64 {
	if a == nil {
		return nil
	}
	return a.HashMode
}

func (a *Attack) GetHashListURL() *string {
	if a == nil {
		return nil
	}
	return a.HashListURL
}

func (a *Attack) GetHashListChecksum() *string {
	if a == nil {
		return nil
	}
	return a.HashListChecksum
}

func (a *Attack) GetURL() *string {
	if a == nil {
		return nil
	}
	return a.URL
}
