// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AttackResourceFile struct {
	// The id of the resource file
	ID int64 `json:"id"`
	// The download URL of the resource file
	DownloadURL string `json:"download_url"`
	// The MD5 checksum of the resource file
	Checksum string `json:"checksum"`
	// The name of the resource file
	FileName string `json:"file_name"`
}

func (a *AttackResourceFile) GetID() int64 {
	if a == nil {
		return 0
	}
	return a.ID
}

func (a *AttackResourceFile) GetDownloadURL() string {
	if a == nil {
		return ""
	}
	return a.DownloadURL
}

func (a *AttackResourceFile) GetChecksum() string {
	if a == nil {
		return ""
	}
	return a.Checksum
}

func (a *AttackResourceFile) GetFileName() string {
	if a == nil {
		return ""
	}
	return a.FileName
}
