// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AuthenticationResponse - The response to a successful agent authentication
type AuthenticationResponse struct {
	Authenticated bool  `json:"authenticated"`
	AgentID       int64 `json:"agent_id"`
}

func (a *AuthenticationResponse) GetAuthenticated() bool {
	if a == nil {
		return false
	}
	return a.Authenticated
}

func (a *AuthenticationResponse) GetAgentID() int64 {
	if a == nil {
		return 0
	}
	return a.AgentID
}
