// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CrackerUpdate struct {
	// A new version of the cracker binary is available
	Available bool `json:"available"`
	// The latest version of the cracker binary
	LatestVersion *string `json:"latest_version,omitempty"`
	// The download URL of the new version
	DownloadURL *string `json:"download_url,omitempty"`
	// The name of the executable
	ExecName *string `json:"exec_name,omitempty"`
	// A message about the update
	Message *string `json:"message,omitempty"`
}

func (c *CrackerUpdate) GetAvailable() bool {
	if c == nil {
		return false
	}
	return c.Available
}

func (c *CrackerUpdate) GetLatestVersion() *string {
	if c == nil {
		return nil
	}
	return c.LatestVersion
}

func (c *CrackerUpdate) GetDownloadURL() *string {
	if c == nil {
		return nil
	}
	return c.DownloadURL
}

func (c *CrackerUpdate) GetExecName() *string {
	if c == nil {
		return nil
	}
	return c.ExecName
}

func (c *CrackerUpdate) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}
