// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// DeviceType - The type of the device
type DeviceType string

const (
	DeviceTypeCPU DeviceType = "CPU"
	DeviceTypeGpu DeviceType = "GPU"
)

func (e DeviceType) ToPointer() *DeviceType {
	return &e
}
func (e *DeviceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CPU":
		fallthrough
	case "GPU":
		*e = DeviceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeviceType: %v", v)
	}
}

// DeviceStatus - Status and performance metrics for a single GPU or CPU device
type DeviceStatus struct {
	// The id of the device
	DeviceID int64 `json:"device_id"`
	// The name of the device
	DeviceName string `json:"device_name"`
	// The type of the device
	DeviceType DeviceType `json:"device_type"`
	// The speed of the device
	Speed int64 `json:"speed"`
	// The utilization of the device
	Utilization int64 `json:"utilization"`
	// The temperature of the device, or -1 if unmonitored.
	Temperature int64 `json:"temperature"`
}

func (d *DeviceStatus) GetDeviceID() int64 {
	if d == nil {
		return 0
	}
	return d.DeviceID
}

func (d *DeviceStatus) GetDeviceName() string {
	if d == nil {
		return ""
	}
	return d.DeviceName
}

func (d *DeviceStatus) GetDeviceType() DeviceType {
	if d == nil {
		return DeviceType("")
	}
	return d.DeviceType
}

func (d *DeviceStatus) GetSpeed() int64 {
	if d == nil {
		return 0
	}
	return d.Speed
}

func (d *DeviceStatus) GetUtilization() int64 {
	if d == nil {
		return 0
	}
	return d.Utilization
}

func (d *DeviceStatus) GetTemperature() int64 {
	if d == nil {
		return 0
	}
	return d.Temperature
}
