// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/internal/utils"
	"time"
)

// ErrorMetadata - Additional metadata about an agent error
type ErrorMetadata struct {
	// The date of the error
	ErrorDate time.Time `json:"error_date"`
	// Other metadata
	Other map[string]any `json:"other,omitempty"`
}

func (e ErrorMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ErrorMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ErrorMetadata) GetErrorDate() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.ErrorDate
}

func (e *ErrorMetadata) GetOther() map[string]any {
	if e == nil {
		return nil
	}
	return e.Other
}
