// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// HashcatGuess - Current hashcat guess progress including base and modifier values
type HashcatGuess struct {
	// The base value used for the guess (for example, the mask)
	GuessBase string `json:"guess_base"`
	// The number of times the base value was used
	GuessBaseCount int64 `json:"guess_base_count"`
	// The offset of the base value
	GuessBaseOffset int64 `json:"guess_base_offset"`
	// The percentage completion of the base value
	GuessBasePercentage float64 `json:"guess_base_percentage"`
	// The modifier used for the guess (for example, the wordlist)
	GuessMod string `json:"guess_mod"`
	// The number of times the modifier was used
	GuessModCount int64 `json:"guess_mod_count"`
	// The offset of the modifier
	GuessModOffset int64 `json:"guess_mod_offset"`
	// The percentage completion of the modifier
	GuessModPercentage float64 `json:"guess_mod_percentage"`
	// The mode used for the guess
	GuessMode int64 `json:"guess_mode"`
}

func (h *HashcatGuess) GetGuessBase() string {
	if h == nil {
		return ""
	}
	return h.GuessBase
}

func (h *HashcatGuess) GetGuessBaseCount() int64 {
	if h == nil {
		return 0
	}
	return h.GuessBaseCount
}

func (h *HashcatGuess) GetGuessBaseOffset() int64 {
	if h == nil {
		return 0
	}
	return h.GuessBaseOffset
}

func (h *HashcatGuess) GetGuessBasePercentage() float64 {
	if h == nil {
		return 0.0
	}
	return h.GuessBasePercentage
}

func (h *HashcatGuess) GetGuessMod() string {
	if h == nil {
		return ""
	}
	return h.GuessMod
}

func (h *HashcatGuess) GetGuessModCount() int64 {
	if h == nil {
		return 0
	}
	return h.GuessModCount
}

func (h *HashcatGuess) GetGuessModOffset() int64 {
	if h == nil {
		return 0
	}
	return h.GuessModOffset
}

func (h *HashcatGuess) GetGuessModPercentage() float64 {
	if h == nil {
		return 0.0
	}
	return h.GuessModPercentage
}

func (h *HashcatGuess) GetGuessMode() int64 {
	if h == nil {
		return 0
	}
	return h.GuessMode
}
