// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/internal/utils"
	"time"
)

// HashcatStatusUpdate - A hashcat status update submitted by an agent during task execution
type HashcatStatusUpdate struct {
	// The original line from hashcat
	OriginalLine string `json:"original_line"`
	// The time the status was received
	Time time.Time `json:"time"`
	// The session name
	Session string `json:"session"`
	// Current hashcat guess progress including base and modifier values
	HashcatGuess HashcatGuess `json:"hashcat_guess"`
	// The status of the task
	Status int64 `json:"status"`
	// The target of the task
	Target string `json:"target"`
	// The progress of the task
	Progress []int64 `json:"progress"`
	// The restore point of the task
	RestorePoint int64 `json:"restore_point"`
	// The number of recovered hashes
	RecoveredHashes []int64 `json:"recovered_hashes"`
	// The number of recovered salts
	RecoveredSalts []int64 `json:"recovered_salts"`
	// The number of rejected guesses
	Rejected int64 `json:"rejected"`
	// The status of the devices used for the task
	DeviceStatuses []DeviceStatus `json:"device_statuses"`
	// The time the task started.
	TimeStart time.Time `json:"time_start"`
	// The estimated time of completion.
	EstimatedStop time.Time `json:"estimated_stop"`
}

func (h HashcatStatusUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HashcatStatusUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HashcatStatusUpdate) GetOriginalLine() string {
	if h == nil {
		return ""
	}
	return h.OriginalLine
}

func (h *HashcatStatusUpdate) GetTime() time.Time {
	if h == nil {
		return time.Time{}
	}
	return h.Time
}

func (h *HashcatStatusUpdate) GetSession() string {
	if h == nil {
		return ""
	}
	return h.Session
}

func (h *HashcatStatusUpdate) GetHashcatGuess() HashcatGuess {
	if h == nil {
		return HashcatGuess{}
	}
	return h.HashcatGuess
}

func (h *HashcatStatusUpdate) GetStatus() int64 {
	if h == nil {
		return 0
	}
	return h.Status
}

func (h *HashcatStatusUpdate) GetTarget() string {
	if h == nil {
		return ""
	}
	return h.Target
}

func (h *HashcatStatusUpdate) GetProgress() []int64 {
	if h == nil {
		return []int64{}
	}
	return h.Progress
}

func (h *HashcatStatusUpdate) GetRestorePoint() int64 {
	if h == nil {
		return 0
	}
	return h.RestorePoint
}

func (h *HashcatStatusUpdate) GetRecoveredHashes() []int64 {
	if h == nil {
		return []int64{}
	}
	return h.RecoveredHashes
}

func (h *HashcatStatusUpdate) GetRecoveredSalts() []int64 {
	if h == nil {
		return []int64{}
	}
	return h.RecoveredSalts
}

func (h *HashcatStatusUpdate) GetRejected() int64 {
	if h == nil {
		return 0
	}
	return h.Rejected
}

func (h *HashcatStatusUpdate) GetDeviceStatuses() []DeviceStatus {
	if h == nil {
		return []DeviceStatus{}
	}
	return h.DeviceStatuses
}

func (h *HashcatStatusUpdate) GetTimeStart() time.Time {
	if h == nil {
		return time.Time{}
	}
	return h.TimeStart
}

func (h *HashcatStatusUpdate) GetEstimatedStop() time.Time {
	if h == nil {
		return time.Time{}
	}
	return h.EstimatedStop
}
