// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// HeartbeatResponseState - The state of the agent:
//   - `pending` - The agent needs to perform the setup process again.
//   - `active` - The agent is ready to accept tasks, all is good.
//   - `error` - The agent has encountered an error and needs to be checked.
//   - `stopped` - The agent has been stopped by the user.
//   - `offline` - The agent has not checked in recently and is considered offline.
type HeartbeatResponseState string

const (
	HeartbeatResponseStateActive  HeartbeatResponseState = "active"
	HeartbeatResponseStateError   HeartbeatResponseState = "error"
	HeartbeatResponseStateOffline HeartbeatResponseState = "offline"
	HeartbeatResponseStatePending HeartbeatResponseState = "pending"
	HeartbeatResponseStateStopped HeartbeatResponseState = "stopped"
)

func (e HeartbeatResponseState) ToPointer() *HeartbeatResponseState {
	return &e
}
func (e *HeartbeatResponseState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "active":
		fallthrough
	case "error":
		fallthrough
	case "offline":
		fallthrough
	case "pending":
		fallthrough
	case "stopped":
		*e = HeartbeatResponseState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for HeartbeatResponseState: %v", v)
	}
}

// HeartbeatResponse - The response to an agent heartbeat
type HeartbeatResponse struct {
	// The state of the agent:
	//                        * `pending` - The agent needs to perform the setup process again.
	//                        * `active` - The agent is ready to accept tasks, all is good.
	//                        * `error` - The agent has encountered an error and needs to be checked.
	//                        * `stopped` - The agent has been stopped by the user.
	//                        * `offline` - The agent has not checked in recently and is considered offline.
	State HeartbeatResponseState `json:"state"`
}

func (h *HeartbeatResponse) GetState() HeartbeatResponseState {
	if h == nil {
		return HeartbeatResponseState("")
	}
	return h.State
}
