// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Severity - The severity of the error:
//   - `info` - Informational message, no action required.
//   - `warning` - Non-critical error, no action required. Anticipated, but not necessarily problematic.
//   - `minor` - Minor error, no action required. Should be investigated, but the task can continue.
//   - `major` - Major error, action required. The task should be investigated and possibly restarted.
//   - `critical` - Critical error, action required. The task should be stopped and investigated.
//   - `fatal` - Fatal error, action required. The agent cannot continue with the task and should not be reattempted.
type Severity string

const (
	SeverityInfo     Severity = "info"
	SeverityWarning  Severity = "warning"
	SeverityMinor    Severity = "minor"
	SeverityMajor    Severity = "major"
	SeverityCritical Severity = "critical"
	SeverityFatal    Severity = "fatal"
)

func (e Severity) ToPointer() *Severity {
	return &e
}
func (e *Severity) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "info":
		fallthrough
	case "warning":
		fallthrough
	case "minor":
		fallthrough
	case "major":
		fallthrough
	case "critical":
		fallthrough
	case "fatal":
		*e = Severity(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Severity: %v", v)
	}
}

// SubmitErrorRequest - Error details reported by the agent
type SubmitErrorRequest struct {
	// The error message
	Message string `json:"message"`
	// Additional metadata about an agent error
	Metadata *ErrorMetadata `json:"metadata,omitempty"`
	// The severity of the error:
	//                        * `info` - Informational message, no action required.
	//                        * `warning` - Non-critical error, no action required. Anticipated, but not necessarily problematic.
	//                        * `minor` - Minor error, no action required. Should be investigated, but the task can continue.
	//                        * `major` - Major error, action required. The task should be investigated and possibly restarted.
	//                        * `critical` - Critical error, action required. The task should be stopped and investigated.
	//                         * `fatal` - Fatal error, action required. The agent cannot continue with the task and should not be reattempted.
	Severity Severity `json:"severity"`
	// The agent that caused the error
	AgentID int64 `json:"agent_id"`
	// The task that caused the error, if any
	TaskID *int64 `json:"task_id,omitempty"`
}

func (s *SubmitErrorRequest) GetMessage() string {
	if s == nil {
		return ""
	}
	return s.Message
}

func (s *SubmitErrorRequest) GetMetadata() *ErrorMetadata {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *SubmitErrorRequest) GetSeverity() Severity {
	if s == nil {
		return Severity("")
	}
	return s.Severity
}

func (s *SubmitErrorRequest) GetAgentID() int64 {
	if s == nil {
		return 0
	}
	return s.AgentID
}

func (s *SubmitErrorRequest) GetTaskID() *int64 {
	if s == nil {
		return nil
	}
	return s.TaskID
}
