// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TaskAbandonResponse - The response to a successful task abandon request
type TaskAbandonResponse struct {
	Success *bool   `json:"success,omitempty"`
	State   *string `json:"state,omitempty"`
}

func (t *TaskAbandonResponse) GetSuccess() *bool {
	if t == nil {
		return nil
	}
	return t.Success
}

func (t *TaskAbandonResponse) GetState() *string {
	if t == nil {
		return nil
	}
	return t.State
}
