// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/internal/utils"
	"time"
)

// Status - The status of the task
type Status string

const (
	StatusPending   Status = "pending"
	StatusRunning   Status = "running"
	StatusCompleted Status = "completed"
	StatusExhausted Status = "exhausted"
	StatusAbandoned Status = "abandoned"
	StatusFailed    Status = "failed"
	StatusPaused    Status = "paused"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "running":
		fallthrough
	case "completed":
		fallthrough
	case "exhausted":
		fallthrough
	case "abandoned":
		fallthrough
	case "failed":
		fallthrough
	case "paused":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

// Task - A unit of work assigned to an agent for a specific attack
type Task struct {
	// The id of the task
	ID int64 `json:"id"`
	// The id of the attack
	AttackID int64 `json:"attack_id"`
	// The time the task was started
	StartDate time.Time `json:"start_date"`
	// The status of the task
	Status Status `json:"status"`
	// The offset of the keyspace
	Skip *int64 `json:"skip,omitempty"`
	// The limit of the keyspace
	Limit *int64 `json:"limit,omitempty"`
}

func (t Task) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Task) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Task) GetID() int64 {
	if t == nil {
		return 0
	}
	return t.ID
}

func (t *Task) GetAttackID() int64 {
	if t == nil {
		return 0
	}
	return t.AttackID
}

func (t *Task) GetStartDate() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.StartDate
}

func (t *Task) GetStatus() Status {
	if t == nil {
		return Status("")
	}
	return t.Status
}

func (t *Task) GetSkip() *int64 {
	if t == nil {
		return nil
	}
	return t.Skip
}

func (t *Task) GetLimit() *int64 {
	if t == nil {
		return nil
	}
	return t.Limit
}
