// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/internal/utils"
	"time"
)

type TaskStatus struct {
	// The original line from hashcat
	OriginalLine string `json:"original_line"`
	// The time the status was received
	Time time.Time `json:"time"`
	// The session name
	Session      string       `json:"session"`
	HashcatGuess HashcatGuess `json:"hashcat_guess"`
	// The status of the task
	Status int64 `json:"status"`
	// The target of the task
	Target string `json:"target"`
	// The progress of the task
	Progress []int64 `json:"progress"`
	// The restore point of the task
	RestorePoint int64 `json:"restore_point"`
	// The number of recovered hashes
	RecoveredHashes []int64 `json:"recovered_hashes"`
	// The number of recovered salts
	RecoveredSalts []int64 `json:"recovered_salts"`
	// The number of rejected guesses
	Rejected int64 `json:"rejected"`
	// The status of the devices used for the task
	DeviceStatuses []DeviceStatus `json:"device_statuses"`
	// The time the task started.
	TimeStart time.Time `json:"time_start"`
	// The estimated time of completion.
	EstimatedStop time.Time `json:"estimated_stop"`
}

func (t TaskStatus) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskStatus) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaskStatus) GetOriginalLine() string {
	if t == nil {
		return ""
	}
	return t.OriginalLine
}

func (t *TaskStatus) GetTime() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.Time
}

func (t *TaskStatus) GetSession() string {
	if t == nil {
		return ""
	}
	return t.Session
}

func (t *TaskStatus) GetHashcatGuess() HashcatGuess {
	if t == nil {
		return HashcatGuess{}
	}
	return t.HashcatGuess
}

func (t *TaskStatus) GetStatus() int64 {
	if t == nil {
		return 0
	}
	return t.Status
}

func (t *TaskStatus) GetTarget() string {
	if t == nil {
		return ""
	}
	return t.Target
}

func (t *TaskStatus) GetProgress() []int64 {
	if t == nil {
		return []int64{}
	}
	return t.Progress
}

func (t *TaskStatus) GetRestorePoint() int64 {
	if t == nil {
		return 0
	}
	return t.RestorePoint
}

func (t *TaskStatus) GetRecoveredHashes() []int64 {
	if t == nil {
		return []int64{}
	}
	return t.RecoveredHashes
}

func (t *TaskStatus) GetRecoveredSalts() []int64 {
	if t == nil {
		return []int64{}
	}
	return t.RecoveredSalts
}

func (t *TaskStatus) GetRejected() int64 {
	if t == nil {
		return 0
	}
	return t.Rejected
}

func (t *TaskStatus) GetDeviceStatuses() []DeviceStatus {
	if t == nil {
		return []DeviceStatus{}
	}
	return t.DeviceStatuses
}

func (t *TaskStatus) GetTimeStart() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.TimeStart
}

func (t *TaskStatus) GetEstimatedStop() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.EstimatedStop
}
