// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateAgentRequest - Agent system information submitted on registration or update
type UpdateAgentRequest struct {
	// The id of the agent
	ID int64 `json:"id"`
	// The hostname of the agent
	HostName string `json:"host_name"`
	// The signature of the client
	ClientSignature string `json:"client_signature"`
	// The operating system of the agent
	OperatingSystem string   `json:"operating_system"`
	Devices         []string `json:"devices"`
}

func (u *UpdateAgentRequest) GetID() int64 {
	if u == nil {
		return 0
	}
	return u.ID
}

func (u *UpdateAgentRequest) GetHostName() string {
	if u == nil {
		return ""
	}
	return u.HostName
}

func (u *UpdateAgentRequest) GetClientSignature() string {
	if u == nil {
		return ""
	}
	return u.ClientSignature
}

func (u *UpdateAgentRequest) GetOperatingSystem() string {
	if u == nil {
		return ""
	}
	return u.OperatingSystem
}

func (u *UpdateAgentRequest) GetDevices() []string {
	if u == nil {
		return []string{}
	}
	return u.Devices
}
